language: node_js
node_js:
  - "10"
services:
  - mongodb
before_install:
  - cd backend
install:
  - npm install
  - npm run build
before_script:
  - sleep 15
  - mongo DocSort --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
