language: node_js
node_js:
  - "10"
services:
  - mongodb
mongodb:
   database: test123
mongo:
   database: test1456
before_install:
  - cd backend
install:
  - npm install
  - npm run build
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
